### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Update dependancies and bump to `0.1.0`. access-control good enough to ave at least a minor version! :)

### CODE REVIEW

**Comment by lpinca** [comment]
Hi,
I would bump the version to `1.0.0`. The reason for the major version update is that we dropped support for node 0.8.
Anyway let us update the module version, and thank you for your contribution.

**Comment by AdrieanKhisbe** [comment]
Hey, I can quickly rework the last commit to 1.0.0 if you want to
:)

**Comment by lpinca** [comment]
just remove it :)

**Comment by AdrieanKhisbe** [comment]
okey ;)

**Comment by AdrieanKhisbe** [comment]
voilà

**Comment by lpinca** [comment]
Mercì.

**Comment by AdrieanKhisbe** [comment]
de rien :)

**Comment by lpinca** [comment]
Published 1.0.0.

**Pull request merged**
